config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy] 
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'welcome#index'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'my_friends', to: 'users#my_friends'
  get 'search_stock', to: 'stocks#search'
  get 'search_friend', to: 'users#search'

  resources :friendships, only: [:create, :destroy] 
  resources :users, only: [:show]
end

app/views/friends/_list.html.erb
<p></p>
<div class="row">
  <div class="col-9">
    <table class="table table-bordered table-hover">
      <thead>
        <th scope="col">First Name</th>
        <th scope="col">Last Name</th>
        <th scope="col">Email</th>
        <th scope="col">Actions</th>
      </thead>
      <tbody>
        <% @friends.each do |friend| %>
          <tr>
            <td><%= friend.first_name %></td>
            <td><%= friend.last_name %></td>
            <td><%= friend.email %></td>
            <td>
              <%= link_to 'View profile', user_path(friend), class: 'btn btn-sm btn-primary' %>
              <% if current_user == @user %>
                <%= link_to 'Stop Following', friendship_path(friend), method: :delete, 
                                              data: { confirm: "Are you sure?" },
                                              class: 'btn btn-sm btn-secondary' %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>