config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy] 
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'welcome#index'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'my_friends', to: 'users#my_friends'
  get 'search_stock', to: 'stocks#search'
  get 'search_friend', to: 'users#search'

  resources :friendships, only: [:create, :destroy] 
  resources :users, only: [:show]
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks 

  validates :name, :ticker, presence: true 

  # ATENCION!!! 
  #   Este metodo requiere de una subscripcion activa al servicio de IEX CLOUD para funcionar
  #   correctamente y obtener cotizaciones reales y actuales de stocks.-
  #
  def self.new_lookup(ticker_symbol) 
    # Recupero las credenciales de mi servicio IEX Cloud desde el YAML de credenciales
    # del proyecto Rails (donde las tengo almacenadas de forma segura bajo el item "iex_client").-
    # Me devuelve un hash con los tokens publico y privado y el link de endpoint que luego
    # uso para establecer la conexion al servicio.-
    #
    iex_client = Rails.application.credentials.iex_client

    # Establezco la conexión con la API de IEX Cloud usando mis credenciales.-
    #
    client = IEX::Api::Client.new(
      publishable_token:  iex_client[:publishable_token],
      secret_token:       iex_client[:secret_token],
      endpoint:           iex_client[:endpoint]
    )

    # Antes de invocar la API, inicio un bloque "begin/rescue" para el caso en que el usuario
    # haya ingresado un 'ticker' invalido y la API me devuelva una excepción, en cuyo caso
    # la interceptamos y simplemente devolvemos 'nil' como resultado de la función.-
    #
    begin 
      # Creo una nueva instancia de la clase "Stock" para que el metodo ya devuelva un objeto
      # armado con los datos necesarios (definidos previamente en el modelo y la db, que serian 
      # "ticker", "nombre" y "precio")
      #
      # Para ello en vez de usar el metodo "price()" de la API de IEX, uso "quote()" que me
      # trae todos los datos de una.-
      #
      quote = client.quote(ticker_symbol)

      # Ahora creo el objeto de la clase Stock (es decir, en la que estamos aqui mismo, por eso 
      # no hace falta hacer "Stock.new()" sino solo "new()") pasandole los datos que me devolvio
      # la API de IEX
      #
      new(
        ticker:       quote.symbol, 
        name:         quote.company_name, 
        last_price:   quote.latest_price
      )
    rescue => exception
      # En caso de que la llamada a "quote()" haya devuelto error, aqui interceptamos la excepción para
      # que no se propague hacia arriba y simplemente devolvemos 'nil' como resultado final
      #
      # return nil

      # *** PARCHE SIN EL SERVICIO DE IEX CLOUD ***
      #
      # Como se me venció el trial de 7 dias, pongo este parche que lo que hace es buscar el Stock
      # dentro de los que ya tenia cargados en le base de datos, y si no devuelve nulo.-
      find_by(ticker: ticker_symbol)
    end
  end

  # Metodo de clase para verificar si un Ticker ya existe en la DB de Stocks, o no
  def self.check_db(ticker_symbol)
    # Equivale a "Stock.where()" porque al estar justo aqui en la clase Stock, queda implícita
    where(ticker: ticker_symbol).first
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  def search

    # If a ticker was sent, search for the stock
    if params[:stock].present?

      @stock = Stock.new_lookup(params[:stock])

      # If it was an invalid ticker...
      if !@stock
        flash.now[:alert] = "Invalid entry. Please enter a valid symbol to search"
      end
    else
        flash.now[:alert] = "Please enter a symbol to search"
    end

    # AJAX Response - Renders the partial in both success and error scenarios
    #                 sending either a valid Stock or an error message 
    respond_to do | format |
      format.js { render partial: 'users/result_js' }
    end
  end

end

app/views/stocks/_list.html.erb
<p></p>
<div class="row">
  <div class="col-9">
    <table class="table table-bordered table-hover">
      <thead>
        <th scope="col">Ticker</th>
        <th scope="col">Name</th>
        <th scope="col">Price</th>
        <th scope="col">Actions</th>
      </thead>
      <tbody>
        <% @stocks.each do |stock| %>
          <tr>
            <th scope="row"><%= stock.ticker %></th>
            <td><%= stock.name %></td>
            <td><%= stock.last_price %></td>
            <td>
              <% if current_user == @user %>
                <%= link_to 'Remove', user_stock_path(stock), method: :delete, 
                                      data: { confirm: "Are you sure?" },
                                      class: 'btn btn-sm btn-primary' %>
              <% else %>
                <% if current_user.stocks.include?(stock) %>
                  <span class="btn btn-secondary badge">Already tracking</span>
                <% else %>
                  <% if current_user.stocks.count < 10 %>
                    <%= link_to 'Add to portfolio', user_stocks_path(user: current_user, ticker: stock.ticker), 
                                      class: "btn btn-sm btn-primary", method: :post %>
                  <% end %>
                <% end %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>