config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy] 
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'welcome#index'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'my_friends', to: 'users#my_friends'
  get 'search_stock', to: 'stocks#search'
  get 'search_friend', to: 'users#search'

  resources :friendships, only: [:create, :destroy] 
  resources :users, only: [:show]
end

app/models/user.rb
class User < ApplicationRecord
  # Relacion "n a n" entre usuarios y stocks: 
  has_many :user_stocks
  has_many :stocks, through: :user_stocks

  # Ralacion "n a n" entre usuarios y usuarios "amigos":
  has_many :friendships
  has_many :friends, through: :friendships
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name
    "Anonymous"
  end

  def stock_already_tracked?(ticker_symbol)
    # Primero verifica que el stock a seguir ya exista en la BD.-
    # Si no existe, significa que ningun usuario lo esta siguiendo aun.-
    stock = Stock.check_db(ticker_symbol)
    return false unless stock 

    # Si el stock ya existe en nuestra DB, es que al menos algun usuario lo esta 
    # siguiendo, aunque no necesariamente el actual que lo esta solicitando.-
    # Entones, verifico si el ID del stock en cuestion ya existe en la coleccion
    # de stocks del usuario actual:
    stocks.where(id: stock.id).exists?  # devuelve boolean, que a su vez es el resultado de la funcion
  end

  def under_stock_limit?
    # Pusimos como limite que solo pueda seguir hasta 10 stocks
    stocks.count < 10     # devuelve boolean, que a su vez es el resultado de la funcion
  end
    
  def can_track_stock?(ticker_symbol)
    # Si aun esta bajo el limite de 10 stocks y ya no estaba siguiendo ese ticker: da TRUE
    under_stock_limit? && !stock_already_tracked?(ticker_symbol)
  end

  def self.search(entry)
    # Aqui utilizamos el metodo de clase "User.where(...)" simplemente como "where()", pues al 
    # estar aqui en el Users Controller, la clase "User" está implícita.-
    #
    # A su vez, anteponemos "self" en la declaracion de la funcion para que nuestro metodo "search()" 
    # tambien sea un metodo de clase (es decir utilitario) y se pueda invocar desde cualquier lugar
    # de la app como "User.search(...)"
    #
    # Funcionamiento:
    #
    # Hago las tres queries a la BD (por nombre, apellido y mail) utilzando like por lo cual pueden venir
    # multiples resultados en cada una, y a su vez estar duplicados, por ejemplo se busca un nombre que
    # es el apellido de alguien y a su vez es parte de su direccion de correo electronico.-
    #
    # Para ello, concateno las tres busquedas y al resultado le aplico el metodo "uniq" de Rails para 
    # eliminar duplicados del mismo.-
    #
    entry.strip!  # Elimina espacios alrededor del string de busqueda

    matches = ( 
      where( "first_name like ?", "%#{entry}%" ) +
      where( "last_name  like ?", "%#{entry}%" ) +
      where( "email      like ?", "%#{entry}%" )
    ).uniq
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @user = current_user
    @stocks = @user.stocks
  end

  def my_friends
    @user = current_user
    @friends = @user.friends
  end

  def show
    @user = User.find(params[:id])
    @stocks = @user.stocks
    @friends = @user.friends
  end

  def search
    entry = params[:friend] 
   
    if entry.present?
      @friends = User.search(entry)
      @friends.delete(current_user)  # avoids listing the logged user himself in the search results

      if @friends.empty? 
        flash[:alert] = "Sorry, could not find the user"     
      end
    else
      flash[:alert] = "Please enter a name or email address to search"
    end
   
    respond_to do | format |
      format.js { render partial: 'users/friend_js' }
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_friend.html.erb
<p></p>

<div class="results-block">
  <%= render 'layouts/messages' %>
</div>

<% if @friends && !@friends.empty? %>
  <div class="card bg-light mb-3 card-body results-block">
    <table class="col-md-12">
      <tbody>
  
        <% @friends.each do |friend| %>
          <tr>
            <td><strong>Name: </strong> <%= friend.full_name %></td>
            <td><strong>Email: </strong> <%= friend.email %></td>
            <td>
              <strong>Actions: </strong> 
              <%= link_to 'View Profile', user_path(friend), class: "btn btn-sm btn-success" %>
              <% if !current_user.friends.include?(friend) %>
                <%= link_to 'Follow', friendships_path(id: friend), class: "btn btn-sm btn-success", method: :post %>
              <% else %>
                <span class="btn btn-secondary badge">You are already friends</span>
              <% end %>
            </td>
          </tr>
        <% end %>

      </tbody>
    </table>
  </div>
<% end %>

app/views/users/_friend_js.js.erb
document.querySelector('#result').innerHTML = "<%= j render 'users/friend' %>"

app/views/users/_result.html.erb
<p></p>

<div class="results-block">
  <%= render 'layouts/messages' %>
</div>

<% if @stock %>
  <div class="card bg-light mb-3 card-body results-block">
  
    <strong>Symbol: </strong> <%= @stock.ticker %>
    <strong>Name: </strong> <%= @stock.name %>
    <strong>Price: </strong> <%= @stock.last_price %>

    <% if current_user.can_track_stock?(@stock.ticker) %>
      <%= link_to 'Add to portfolio', user_stocks_path(user: current_user, ticker: @stock.ticker), 
                                      class: "btn btn-sm btn-primary", method: :post %>
    <% else %>
      <span class="btn btn-primary badge">
        You are already tracking 
        <% if !current_user.under_stock_limit? %>
          10 stocks
        <% else %>
          this stock
        <% end %>
      </span>
    <% end %>

  </div>
<% end %>

app/views/users/_result_js.js.erb
document.querySelector('#result').innerHTML = "<%= j render 'users/result' %>"

app/views/users/my_friends.html.erb
<h1>My Friends</h1>

<div class="search-area">
  <h3>Search Friends</h3>
  <%= form_tag search_friend_path, remote: true, data: {turbo: false}, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :friend, params[:friend], placeholder: "Name or email", autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-sm-3 no-left-padding">
        <%= button_tag type: :submit, class: "btn btn-success" do %>
          <%= fa_icon 'search 2x' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div id="result">

</div>

<% if !@friends.empty? %>
  <%= render 'friends/list' %>
<% end %>

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>

<div class="search-area">
  <h3>Search Stocks</h3>
  <%= form_tag search_stock_path, remote: true, data: {turbo: false}, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :stock, params[:stock], placeholder: "Stock ticker symbol", autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-sm-3 no-left-padding">
        <%= button_tag type: :submit, class: "btn btn-success" do %>
          <!-- Instalamos el Gem "Font Awesome" que nos da iconos varios a traves del uso del tag "fa_icon" -->
          <%= fa_icon 'search 2x' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div id="result">

</div>

<% if !@stocks.empty? %>
  <%= render 'stocks/list' %>
<% end %>

app/views/users/show.html.erb
<h2>User Details</h2>
<p></p>

<div class="card bg-light mb-3 card-body results-block">
  <table class="col-md-12">
    <tbody>
      <tr>
        <td><strong>Name: </strong> <%= @user.full_name %></td>
        <td><strong>Email: </strong> <%= @user.email %></td>
        <td>
          <% if current_user == @user %>
            <span class="btn btn-primary badge">Hey, that's me!</span>
          <% else %>
            <% if current_user.friends.include?(@user) %>
              <span class="btn btn-secondary badge">You are already friends</span>
            <% else %>
              <%= link_to 'Follow', friendships_path(id: @user), class: "btn btn-sm btn-success", method: :post %>
            <% end %>
          <% end %>

        </td>
      </tr>
    </tbody>
  </table>
</div>

<% if !@stocks.empty? %>
  <p class="lead"><%= @user.first_name %>'s stocks:</p>
  <%= render 'stocks/list' %>
<% else %>
  <p class="lead"><%= @user.first_name %> is not tracking any stocks</p>
<% end %>

<% if !@friends.empty? %>
  <p class="lead"><%= @user.first_name %>'s friends:</p>
  <%= render 'friends/list' %>
<% else %>
  <p class="lead"><%= @user.first_name %> is not following any friends</p>
<% end %>